config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :datebookings do
   resources :timetebookings
  end

 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datebooking.rb
class Datebooking < ApplicationRecord
	  belongs_to :user
    has_many :timetebookings
    validates :date, presence: true
end

app/models/timetebooking.rb
class Timetebooking < ApplicationRecord
  belongs_to :datebooking
   validates :nome, presence: true
    validates :prenom, presence: true
     validates :telephpne, presence: true
     validates :time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :datebookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/datebookings_controller.rb
class DatebookingsController < ApplicationController
  before_action :set_datebooking, only: [:show, :edit, :update, :destroy]
 
  # GET /datebookings
  # GET /datebookings.json
  def index
    @datebookings = Datebooking.all
  end

  # GET /datebookings/1
  # GET /datebookings/1.json
  def show
      @datebookings = Datebooking.all
   @com = @datebooking.timetebookings.count
    if @com == 15
     @datebooking.etat = false
    else
      @res = 15 - @com
      @datebooking.etat = true  
    end
  end

  # GET /datebookings/new
  def new
    @datebooking = Datebooking.new
  end

  # GET /datebookings/1/edit
  def edit
  end

  # POST /datebookings
  # POST /datebookings.json
  def create
    @datebooking = Datebooking.new(datebooking_params)

    respond_to do |format|
      if @datebooking.save
        format.html { redirect_to @datebooking, notice: 'Datebooking was successfully created.' }
        format.json { render :show, status: :created, location: @datebooking }
      else
        format.html { render :new }
        format.json { render json: @datebooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datebookings/1
  # PATCH/PUT /datebookings/1.json
  def update
    respond_to do |format|
      if @datebooking.update(datebooking_params)
        format.html { redirect_to @datebooking, notice: 'Datebooking was successfully updated.' }
        format.json { render :show, status: :ok, location: @datebooking }
      else
        format.html { render :edit }
        format.json { render json: @datebooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datebookings/1
  # DELETE /datebookings/1.json
  def destroy
    @datebooking.destroy
    respond_to do |format|
      format.html { redirect_to datebookings_url, notice: 'Datebooking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datebooking
      @datebooking = Datebooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datebooking_params
      params.require(:datebooking).permit(:date, :etat, :user_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  	 @datebookings = Datebooking.all
  end
end

app/controllers/timetebookings_controller.rb
class TimetebookingsController < ApplicationController
	before_action :set_timetebooking, only: [:repa,]
		def create


    @datebooking = Datebooking.find(params[:datebooking_id])
  
      @timebooking = @datebooking.timetebookings.create(timebooking_params)
      redirect_to datebooking_path(@datebooking)
     
    
	end






   private 
   def timebooking_params
   params.require(:timetebooking).permit(:nome, :prenom, :telephpne , :time) 

   	
   end


end

   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datebookings_helper.rb
module DatebookingsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/timebookings_helper.rb
module TimebookingsHelper
end

app/views/datebookings/_form.html.erb
<%= form_with(model: datebooking, local: true) do |form| %>
  <% if datebooking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(datebooking.errors.count, "error") %> prohibited this datebooking from being saved:</h2>

      <ul>
      <% datebooking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :datebooking_date %>
  </div>
<%= form.hidden_field :user_id, :value => current_user.id %>
  <div class="field">
    <%= form.label :etat %>
    <%= form.check_box :etat, id: :datebooking_etat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/datebookings/edit.html.erb
<h1>Editing Datebooking</h1>

<%= render 'form', datebooking: @datebooking %>

<%= link_to 'Show', @datebooking %> |
<%= link_to 'Back', datebookings_path %>

app/views/datebookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Datebookings</h1>
<strong>hello word</strong>
<h2>hello</h2>
<em>hello</em>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Etat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @datebookings.each do |datebooking| %>
      <tr>
        <td><%= datebooking.date %></td>
        <td><%= datebooking.etat %></td>
        <td><%= link_to 'Show', datebooking %></td>
        <td><%= link_to 'Edit', edit_datebooking_path(datebooking) %></td>
        <td><%= link_to 'Destroy', datebooking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Datebooking', new_datebooking_path %>

app/views/datebookings/new.html.erb
<h1>New Datebooking</h1>

<%= render 'form', datebooking: @datebooking %>

<%= link_to 'Back', datebookings_path %>

app/views/datebookings/show.html.erb
	
<div class="sidenav">
	<a href="/">Home</a>
  <a href="#about">About</a>
  <a href="#services">Services</a>
  <a href="#clients">Clients</a>
  <a href="#contact">Contact</a>
  <button class="dropdown-btn">date  
    <i class="fa fa-caret-down"></i>
  </button>
  <div class="dropdown-container" style="light: 50px;">
  	 <% @datebookings.each do |datebooking| %>
    
       <a href="/datebookings/<%=datebooking.id%>"><%= datebooking.date %> 
       <p>haw zebis</p>
       </a> 
    <%end%>
  </div>
  <a href="#contact">Search</a>
</div>



<div class="main">



<p id="notice"><%= notice %></p>

<p style="text-align: center;">
  <strong>Date:</strong>
  <%= @datebooking.date %>
</p>

<p>
 
  <% if @datebooking.etat == true %>
  <p style="color: green; text-align: center;"> y a encore <%= @res%> rendez vous </p>
  <% else %>
 <p style="text-align: center; color: red">complet</p>
 <%end%>
</p>

<%if @datebooking.etat == true %>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  prendre un rendez vous
</button><%end%>

<%= link_to 'Back', datebookings_path %>
<hr>


<table class="table table-hover " id="myTable">
  <thead>
    <tr>
<%= @count%>
       <th scope="col" >rendez-vous </th>
      <th scope="col">Le nom</th>
      <th scope="col">le prenom </th>
      <th scope="col">telepone </th>
    
    </tr>
  </thead>

  <tbody>
    <tr><% @datebooking.timetebookings.each do |f|%>
    
        <td><%= f.time  %></td>
      <td><%= f.nome %></td>
      <td><%= f.prenom %></td>
        <td><%= f.telephpne %></td>
      

    </tr>
   <%end%>
  </tbody>
</table>





<%= form_for([@datebooking, @datebooking.timetebookings.build]) do |f|  %>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">prendre un rendez vous </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
    <p> 
<div class="row"><div class="col-md-6">
  <%= f.label  :nome %><br>
  <%= f.text_field  :nome ,:class=>"form-control needs-validation"%>
</p>
<p>
  <%= f.label  :prenom %><br>
  <%= f.text_field  :prenom ,:class=>"form-control needs-validation"%>
</p>
<p>
  <%= f.label :telephpne %><br>
  <%= f.text_field :telephpne ,:class=>"form-control needs-validation"%>
</p></div>
<!-- the time local-->
<% @time = Time.parse("8:00")%>

<% @tf = Time.parse("16:01") %><br>

<% @tfl = @tf.strftime("%R") %><br>

<% @timel = @time.strftime("%R") %><br>

<% @tfl = @tfl.to_time + 1800 %>

    
<div class="col-md-3" style="border-right: 1px solid black ">
	<p style="font-size: 20px; border-bottom: 1px solid black;padding-bottom: 10px;text-align: center;">matin</p>
<% for i in 1..15 %>
            <% @etat = false%>


            <% if @timel == "12:00"%>
            <% @time = @time + 3600 %>
             <% @timel = @time.strftime("%R") %>
             </div>
             <div class="col-md-3">
             	<p style="font-size: 20px; border-bottom: 1px solid black;padding-bottom: 10px" >apres midi</p>
            <% end%>



             <% @datebooking.timetebookings.each do |t|%>
                  <% if t.time == @timel  %>
                  <% @etat = true %>
                  <%end%>
             <%end%>
             <%if @etat == false %>
              <% @time = @time + 1800 %>
             <%= f.radio_button :time,  @timel %><%= "-" %> <%= @timel%> 
<br>
            
             <% @timel = @time.strftime("%R") %>
             <%else%>
             <% @t = "X-  " %>
              <%= @t + @timel %> <br>

             <% @time = @time + 1800 %>
             <% @timel = @time.strftime("%R") %>
             <%end%>
<%end%>
</div>

 




</p>
<p>
  
    </div>
</p>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        <input name="commit" value="prendre un rendez-vous" data-disable-with="Create Timetebooking" type="submit" class="btn btn-primary">
      </div>
    </div>
  </div>
</div>
<%end%>



<script>
{
  var table, rows, switching, i, x, y, shouldSwitch;
  table = document.getElementById("myTable");
  switching = true;
  /*Make a loop that will continue until
  no switching has been done:*/
  while (switching) {
    //start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /*Loop through all table rows (except the
    first, which contains table headers):*/
    for (i = 1; i < (rows.length - 1); i++) {
      //start by saying there should be no switching:
      shouldSwitch = false;
      /*Get the two elements you want to compare,
      one from current row and one from the next:*/
      x = rows[i].getElementsByTagName("TD")[0];
      y = rows[i + 1].getElementsByTagName("TD")[0];
      //check if the two rows should switch place:
      if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
        //if so, mark as a switch and break the loop:
        shouldSwitch = true;
        break;
      }
    }
    if (shouldSwitch) {
      /*If a switch has been marked, make the switch
      and mark that a switch has been done:*/
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
    }
  }
}
</script>
<a href="javascript:window.print()">Imprimer</a>

app/views/datebookings/tiemtebookings/show.html.erb
<h1>helllo</h1>

app/views/homes/index.html.erb
<footer class="footer">
 <div class="footer-middle " >
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Address</h4>
          <address>
								<ul class="list-unstyled">
									<li>
                    City Hall<br>
										212  Street<br>
										Lawoma<br>
										735<br>
									</li>
									<li>
										Phone: 0
									</li>
								</ul>
							</address>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Popular Services</h4>
          <ul class="list-unstyled">
            <li><a href="#"></a></li>
            <li><a href="#">Payment Center</a></li>
            <li><a href="#">Contact Directory</a></li>
            <li><a href="#">Forms</a></li>
            <li><a href="#">News and Updates</a></li>
            <li><a href="#">FAQs</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Website Information</h4>
          <ul class="list-unstyled">
            <li><a href="#">Website Tutorial</a></li>
            <li><a href="#">Accessibility</a></li>
            <li><a href="#">Disclaimer</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">FAQs</a></li>
            <li><a href="#">Webmaster</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Popular Departments</h4>
          <ul class="list-unstyled">
            <li><a href="#">Parks and Recreation</a></li>
            <li><a href="#">Public Works</a></li>
            <li><a href="#">Police Department</a></li>
            <li><a href="#">Fire</a></li>
            <li><a href="#">Mayor and City Council</a></li>
            <li>
              <a href="#"></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <!--Footer Bottom-->
          <p class="text-xs-center">&copy; Copyright 2016 - City of USA.  All rights reserved.</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1">
    
<style>
body {
    font-family: "Lato", sans-serif;
    
}

/* Fixed sidenav, full height */
.sidenav {
    height: 100%;
    width: 200px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    padding-top: 20px;
}

/* Style the sidenav links and the dropdown button */
.sidenav a, .dropdown-btn {
    padding: 6px 8px 6px 16px;
    text-decoration: none;
    font-size: 20px;
    color: #818181;
    display: block;
    border: none;
    background: none;
    width: 100%;
    text-align: left;
    cursor: pointer;
    outline: none;
}

/* On mouse-over */
.sidenav a:hover, .dropdown-btn:hover {
    color: #f1f1f1;
}

/* Main content */
.main {
    margin-left: 200px; /* Same as the width of the sidenav */
     /* Increased text to enable scrolling */
    padding: 0px 10px;
}

/* Add an active class to the active dropdown button */
.active {
    background-color: green;
    color: white;
}

/* Dropdown container (hidden by default). Optional: add a lighter background color and some left padding to change the design of the dropdown content */
.dropdown-container {
    display: none;
    background-color: #262626;
    padding-left: 8px;
}

/* Optional: Style the caret down icon */
.fa-caret-down {
    float: right;
    padding-right: 8px;
}

/* Some media queries for responsiveness */
@media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
}
</style>

  </head>

  <body>

  	
    <%= yield %>


















<script>
/* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
var dropdown = document.getElementsByClassName("dropdown-btn");
var i;

for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
      dropdownContent.style.display = "none";
    } else {
      dropdownContent.style.display = "block";
    }
  });
}
</script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>